### ISSUE TITLE
How to add polyline node to the path

### ISSUE THREAD

**Issue by aminasadi0** [Dandarawy/Unity3DPolylineEditor#1]
Hi,

Thanks for your effort. I'm quite new to Unity. I'm looking for better way to create paths in my android application with the possibility to fly over the view much like a map (e.g. Google map) but the map is actually a graph with vertices and edges. I would guess Unity would be easier than manually creating Android views. I'm wonder if it is possible to add nodes to the polygon on the fly in the script/Android as my graph extends during time.

Bests,

**Comment by Dandarawy** [comment]
If you want to add nodes in runtime you  can simple write:
`path.nodes.Add(newNode)`
for more info on how to get the path object itself please check Example_1->PathMovement script
please note that this library is a unity editor extension, it has been written to work in design time, if you want to create a path in runtime you can easily create a `List<Vector3>` and append your nodes to this list

**Comment by aminasadi0** [comment]
Alright. Seems like I was a little bit misunderstood. The thing is, I wanted to use something like Line Renderer to draw a polyline. But LineRenderer has some issues with the line width. Everyone is suggesting to use Vectrosity. But I needed an opensource, free alternative. That's why I was trying to get the polyline editor to work. Seems like it is just for editing purposes and not for being drawn on the game scene? right?

**Comment by Dandarawy** [comment]
yes, you are right. This tool can help you to edit your line in editor not in runtime.
