### ISSUE TITLE
Great assets but not work since old api deprecated

### ISSUE THREAD

**Issue by liangwei191** [Dandarawy/Unity3DPolylineEditor#2]
Since unity has changed the button.on(bla bla bla
for editor click events.The polyons can not be modified anymore.
But the node still can be move or create after chage the new event function to fix the error.
Hope you could take a look into it.
problem occured.Unity 2019.x Unity 2020.x 
Thank you very much.

**Comment by Unity3D-Hardik** [comment]
Hi. 
Did you resolve the issue? 
Can you update the source or guide to resolving the issue !! 

is that work with android and iOS runtime?

**Comment by liangwei191** [comment]
No.I am wait reply for the author.I just gived up.It is quite hard to deal with because I don't think my code got anything changed with the origin one but it doesn't work.
    On Tuesday, April 6, 2021, 05:04:06 AM GMT+8, Hardik Shah ***@***.***> wrote:  
 
 


Hi.
Did you resolve the issue?
Can you update the source or guide to resolving the issue !!

is that work with android and iOS runtime?

**Comment by liangwei191** [comment]
Oh,iam sorry if you are the author.I would have a try.Great thanks!    On Tuesday, April 6, 2021, 05:04:06 AM GMT+8, Hardik Shah ***@***.***> wrote:  
 
 


Hi.
Did you resolve the issue?
Can you update the source or guide to resolving the issue !!

is that work with android and iOS runtime?

**Comment by liangwei191** [comment]
Haha,sorry sorry again.I misunderstand your reply for asking resolving the problem.I got a post on unity forum and uploaded a project packed with 2020 or 2019
Here is the linkHandles.Button( seems not work on 2019 since its api has changed


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Handles.Button( seems not work on 2019 since its api has changed

if (Handles.Button(mousePos, Quaternion.identity, handleSize * 0.1f, handleSize, HandleFunc)) { //cl...
 |

 |

 |


It doesnt work on editor for editing the map but it still and add or move nodes.quite strange.If you have time you could have a check.Thanks again.

    On Tuesday, April 6, 2021, 05:04:06 AM GMT+8, Hardik Shah ***@***.***> wrote:  
 
 


Hi.
Did you resolve the issue?
Can you update the source or guide to resolving the issue !!

is that work with android and iOS runtime?

**Comment by liangwei191** [comment]
Yeah. why garbled text here.I've replied by email.
Here is the post I've changed for unity 2020.
I doesn't work on editor for modify the map.
[problem on unity forum](https://forum.unity.com/threads/handles-button-seems-not-work-on-2019-since-its-api-has-changed.1080893/)

**Comment by Dandarawy** [comment]
> Hi.
> Did you resolve the issue?
> Can you update the source or guide to resolving the issue !!
> 
> is that work with android and iOS runtime?

This is editor only tool, doesn't work in runtime

**Comment by Dandarawy** [comment]
Thanks for reporting this issue, I'll have a look at it soon!

**Comment by Dandarawy** [comment]
I've tested the project with unity 2019 and 2020 and it is working fine, there are some warning for some deprecated functions but it is still working totally fine, I'll push some updates to remove deprecated code anyway

**Comment by liangwei191** [comment]
Nonono,I didn't play it in runtime. I just used it for creating node connected maps.Maybe you can take a look of my post.Thanks for your concern.No hurry when you free.

    On Wednesday, April 7, 2021, 11:59:22 AM GMT+8, Abdullah Aldandarawy ***@***.***> wrote:  
 
 



Hi.
Did you resolve the issue?
Can you update the source or guide to resolving the issue !!

is that work with android and iOS runtime?


This is editor only tool, doesn't work in runtime
